### ISSUE TITLE
wrong credentials data loader in mongodb connector

### ISSUE THREAD

**Issue by gonzalocohere** [cohere-ai/quick-start-connectors#12]
### Which connector is affected?

MongoDB

### What is the issue?

dev/load_data.py has:

client = pymongo.MongoClient(
    host=os.environ.get("MONGODB_HOST", "mongo"),
    port=os.environ.get("MONGODB_PORT", 27017),
    username=os.environ.get("MONGODB_ROOT_USERNAME", "root"),
    password=os.environ.get("MONGODB_ROOT_PASSWORD", "example"),
)

instead it should be:
client = pymongo.MongoClient(
   connection_string,
)

**Comment by tianjing-li** [comment]
Taking this now
