### ISSUE TITLE
[DOCS] Asana connector misleading docs.

### ISSUE THREAD

**Issue by llermaly** [cohere-ai/quick-start-connectors#131]
### Which connector is affected?

asana

### What would you like to see improved?

Documentation

### Additional information

The documentation is not clear. I'm following the steps and I'm seeing this error: 

```
{
  "detail": "No authorization token provided",
  "status": 401,
  "title": "Unauthorized",
  "type": "about:blank"
}
```

I set my env vars: 

```
ASANA_AUTH_TYPE=access_token
ASANA_ACCESS_TOKEN=2/12065118.....
ASANA_WORKSPACE_GID=12065.....
ASANA_CONNECTOR_API_KEY=eyJhbGc...
```

I found the API call do not include the bearer token : 

```
curl --location 'http://localhost:5000/search' \
--header 'Content-Type: application/json' \
--data '{
    "query": "BBQ"
  }'
```

After manually putting the header I see an error with the workspace ID because going to admin.asana.com shows a wrong one.

I went to this URL to get the ID:
https://app.asana.com/api/1.0/workspaces

Final request: 

```
curl --location 'http://localhost:5000/search' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer eyJhbGc........' \ <---- Missing from docs
--data '{
    "query": "BBQ"
  }'
```

I would suggest putting together all the env vars needed for each authentication method. Finding that workspace id was required was not straightforward. 

After getting it right all worked nicely. Thanks for this efforts ! I would be glad to rework the docs and create a PR if you like.

**Comment by tianjing-li** [comment]
@llermaly yes please! Documentation changes would be greatly appreciated

**Comment by tianjing-li** [comment]
Actually noticed this is basically repo-wide across all connectors. I will handle updating the documentation instead for all the READMEs and specify that the Bearer token is needed for requests to /search. ty

**Comment by tianjing-li** [comment]
@llermaly glad to hear it's been smooth for you so far. I just opened #136 to update all the curl requests with the required headers, the table idea is good, I'll make a note of it somewhere.

**Comment by llermaly** [comment]
Great! ,  for security reasons all the connectors should be enforced to use the API_KEY . 

Two things I have seen on my journey:

* It is not clear you have to invent an API Key, it took me a while to understand that at the beginning, I was looking for some key on the connector source
* Some connectors (e.g Confluence) allows to not use API_KEY, but then to use it you have to send anything on the API_KEY for it to work
