### ISSUE TITLE
[Confluence] HTML Strip

### ISSUE THREAD

**Issue by llermaly** [cohere-ai/quick-start-connectors#134]
### Which connector is affected?

confluence

### What would you like to see improved?

This is both questions and suggestions:

* Is cohere cleaning the HTML when sending to the API ? 
* If not, do you think removing things like styles from the HTML is advisable in the connector?
* If HTML help with context it we may keep/simplify the tags, and remove styles, right?
* The UI is showing the HTML , that should probably be removed

![image](https://github.com/cohere-ai/quick-start-connectors/assets/8575569/cced7e09-fd83-4632-82ff-fc03770bff72)

Thanks!

**Comment by tianjing-li** [comment]
@walterbm-cohere @daniel-cohere

**Comment by tianjing-li** [comment]
Hey, I've opened #147 which will clean up quite a lot of the HTML by using a different page format
