### ISSUE TITLE
[Confluence] More flexible search

### ISSUE THREAD

**Issue by llermaly** [cohere-ai/quick-start-connectors#137]
### Which connector is affected?

Confluence

### What would you like to see improved?

Currently Confluence API is doing an `AND` query meaning every word must appear in a document.  This is bad because of the nature of the conversations the question will not show up in the documents.

Confluence API have some options with search: 

https://confluence.atlassian.com/doc/confluence-search-syntax-158720.html

We could at least document about this options.

What I'm doing as a workaround is manually entering `OR`s in the queries.

![CleanShot 2024-02-05 at 19 40 19](https://github.com/cohere-ai/quick-start-connectors/assets/8575569/a09a2e2b-d514-48aa-97ad-aa816484692c)

vs

![CleanShot 2024-02-05 at 19 40 51](https://github.com/cohere-ai/quick-start-connectors/assets/8575569/06b9406a-40b5-4cdd-ba4c-0a98efb23f6c)

Not ideal but better than nothing. 

What's your thought on this? Maybe training some intent classifier to do more sophisticated queries? 

Like: 

Detected entities: Emily , Project
(What's Emily doing on this project?) OR (Emily Project)

Appreciate your thoughs @tianjing-li

**Comment by tianjing-li** [comment]
Under the hood we're using their [CQL](https://developer.atlassian.com/server/confluence/advanced-searching-using-cql/) language to run searches, it looks like when multiple keywords appear they must all match within the page, which isn't great. This advanced search page should be documented within the `Limitations` part of the Confluence README

**Comment by llermaly** [comment]
Yeah , I can imagine some workarounds like starting with a regular query and if return 0 results go more flexible using OR's

**Comment by tianjing-li** [comment]
Merged updates PR #147, adds documentation for this aspect
